odimra:
  namespace:
  rootCACert:
  odimraServerCert:
  odimraServerKey:
  odimraRSAPublicKey:
  odimraRSAPrivateKey:
  odimraKafkaClientCert:
  odimraKafkaClientKey:
  odimraEtcdServerCert:
  odimraEtcdServerKey:
