apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation
  namespace: {{ .Values.odimra.namespace }}
  annotations:
    secret.reloader.stakater.com/reload: "odimra-secret"
spec:
  replicas: {{ .Values.ReplicaCount | default 1 }}
  selector:
    matchLabels:
      app: aggregation
  template:
    metadata:
      labels:
        app: aggregation
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      hostname: aggregation
      volumes:
        - name: odimra-config-vol
          projected:
            sources:
            - configMap:
                name: odimra-config
            - configMap:
                name: odimra-platformconfig
        - name: configure-hosts
          configMap:
            name: configure-hosts
            items:
            - key: hosts
              path: host.append
              mode: 0644
        - name: odimra-secret
          secret:
            secretName: odimra-secret
            items:
            - key: rootCAcrt
              path: rootCA.crt
              mode: 0444
            - key: odimra_servercrt
              path: odimra_server.crt
              mode: 0444
            - key: odimra_serverkey
              path: odimra_server.key
              mode: 0444
            - key: odimra_rsapublic
              path: odimra_rsa.public
              mode: 0444
            - key: odimra_rsaprivate
              path: odimra_rsa.private
              mode: 0444
            - key: odimra_kafka_clientcrt
              path: odimra_kafka_client.crt
              mode: 0444
            - key: odimra_kafka_clientkey
              path: odimra_kafka_client.key
              mode: 0444
        - name: odimra-log
          persistentVolumeClaim:
            claimName: odimra-log-claim
      securityContext:
        fsGroup: {{ .Values.odimra.groupID }}
      serviceAccountName: odimra
      containers:
        - name: aggregation
          securityContext:
            privileged: true
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: HA_ENABLED
              value: {{ .Values.odimra.haDeploymentEnabled | quote }}
            - name: ODIM_NAMESPACE
              value: {{ .Values.odimra.namespace | quote }}
          image: aggregation:{{ .Values.odimra.aggregationImageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 45102
          volumeMounts:
            - name: odimra-config-vol
              mountPath: /etc/odimra_config
            - name: configure-hosts
              mountPath: /tmp
            - name: odimra-log
              mountPath: /var/log/odimra_logs
            - name: odimra-secret
              mountPath: /etc/odimra_certs
