odimra:
  redisImageTag: "2.0"
  namespace:
  groupID:
  redisOndiskDataPath:
  redisInmemoryDataPath:
  redisSecondayReplicaCount: 2
  redisMasterSet: primaryset
  redisQuorum: 2
  redisDownAfterMilliseconds: 1000
  redisFailoverTimeout: 3000
  redisParallelSyncs: 1
