odimra:
  namespace:
  groupID:
  haDeploymentEnabled:
grfplugin:
  eventListenerNodePort:
  imageTag: "3.2"
  logPath:
  rootServiceUUID:
  username:
  password:
  host: grfplugin
  eventHost: grfplugin
  lbHost:
  lbPort:
