dellplugin:
  eventListenerNodePort: 30084
  dellPluginRootServiceUUID: 
  username: admin
  password: sTfTyTZFvNj5zU5Tt0TfyDYU-ye3_ZqTMnMIj-LAeXaa8vCnBqq8Ga7zV6ZdfqQCdSAzmaO5AJxccD99UHLVlQ==
  lbHost: 
  lbPort:
  logPath: /var/log/dellplugin_logs
