apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
  namespace: {{ .Values.odimra.namespace }}
  annotations:
    secret.reloader.stakater.com/reload: "odimra-secret"
spec:
  replicas: {{ .Values.ReplicaCount | default 1 }}
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
      name: dapi-envars-fieldref
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 3
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: task      
      hostname: task
      volumes:
        - name: odimra-config-vol
          projected:
            sources:
            - configMap:
                name: odimra-config
            - configMap:
                name: odimra-platformconfig
        - name: configure-hosts
          configMap:
            name: configure-hosts
            items:
            - key: hosts
              path: host.append
              mode: 0644
        - name: odimra-secret
          secret:
            secretName: odimra-secret
            items:
            - key: rootCAcrt
              path: rootCA.crt
              mode: 0444
            - key: odimra_servercrt
              path: odimra_server.crt
              mode: 0444
            - key: odimra_serverkey
              path: odimra_server.key
              mode: 0444
            - key: odimra_rsapublic
              path: odimra_rsa.public
              mode: 0444
            - key: odimra_rsaprivate
              path: odimra_rsa.private
              mode: 0444
            - key: redis_inmemory_password
              path: redis_inmemory_password
              mode: 0444
            - key: redis_ondisk_password
              path: redis_ondisk_password
              mode: 0444
            {{- if eq .Values.odimra.messageBusType "Kafka" }}
            - key: odimra_kafka_clientcrt
              path: odimra_kafka_client.crt
              mode: 0444
            - key: odimra_kafka_clientkey
              path: odimra_kafka_client.key
              mode: 0444
            {{- end }}
        - name: odimra-log
          persistentVolumeClaim:
            claimName: odimra-log-claim
      securityContext:
        fsGroup: {{ .Values.odimra.groupID }}
        runAsUser: {{ .Values.odimra.groupID }}
      containers:
        - name: task
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: HA_ENABLED
              value: {{ .Values.odimra.haDeploymentEnabled | quote }}
            - name: ODIM_NAMESPACE
              value: {{ .Values.odimra.namespace | quote }}
<<<<<<< HEAD
<<<<<<< HEAD
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: task:{{ .Values.odimra.taskImageTag }}
=======
          image: image-registry.openshift-image-registry.svc:5000/odim/task:{{ .Values.odimra.taskImageTag }}
>>>>>>> 8ba4723d (adding changes to related rhocp deployment)
=======
          image: 10.24.1.61:5000/odim/task:{{ .Values.odimra.taskImageTag }}
>>>>>>> 5cd0a891 (updatign the image registry name)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 45105
          volumeMounts:
            - name: odimra-config-vol
              mountPath: /etc/odimra_config
            - name: configure-hosts
              mountPath: /tmp
            - name: odimra-log
              mountPath: /var/log/odimra_logs
            - name: odimra-secret
              mountPath: /etc/odimra_certs
