---
## requirements.yaml contains the definitions required
## for performing pre-reqs on the cluster nodes.

# Below package versions should be updated by user
# only when the particular version is not available
# in the apt cache
keepalived_pkgs:
# - check for the latest version of linux-headers using
# `sudo apt-cache search --names-only "linux-headers-[0-9.-]*-generic" | tail -5 | sort -r`
# - check if the first entry in the list is present in the cache using
# `sudo apt-cache madison <package_name>`
# package_name ex: linux-headers-5.8.0-63-generic
  - linux-headers-5.8.0-63-generic
# - check for the latest version of keepalived in cache using
# `sudo apt-cache madison keepalived`
  - keepalived=1:2.0.19-2
nginx_pkgs:
# - check for the latest version of nginx in cache using
# `sudo apt-cache madison nginx`
  - nginx=1.18.0-0ubuntu1.2

# Below packages should not altered/updated by user
# unless otherwise asked/suggested to do so
docker_dep_pkgs:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
docker_pkgs:
  - docker-ce=5:19.03.12~3-0~ubuntu-bionic
  - docker-ce-cli=5:19.03.12~3-0~ubuntu-bionic
  - containerd.io
docker_pkgs_wo_version:
  - docker-ce
  - docker-ce-cli
  - containerd.io
keepalived_dep_pkgs:
  - net-tools
nginx_dep_pkgs:
  - curl
  - gnupg2
  - ca-certificates
  - lsb-release
nginx_pkgs_wo_version:
  - nginx
  - nginx-common
  - nginx-core
